### ISSUE TITLE
Можно было обойтись без подзапроса

### ISSUE THREAD

**Issue by algolGuru** [m3tro1d/databases#1]
https://github.com/m3tro1d/databases/blob/f7a22736d8cd0eb9c3acca40573731c275712204/lab06/lab6.sql#L43

Можно было в основном запросе сделать еще один join на таблицу production  и после этого join на order да и у тебя два раза проверка на название Фарма
Нужно поправить, можно оптимизировать

**Comment by m3tro1d** [comment]
Исправлено: 4512f3c0a968e8dd90daea01f78a9fab37822ff1
